name: Lint action
run-name: Run lint
on: [push]

jobs:
  lint:
    runs-on: [ubuntu-latest]

    steps:
      - name: Traer repo
        uses: actions/checkout@v4

      - name: Usar nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Instalar dependencias
        working-directory: ./calculadora
        run: npm install

      - name: Ejecutar action
        working-directory: ./calculadora
        run: npm run lint
