name: Test action
run-name: Run test
on: [push]

jobs:
  test:
    runs-on: [ubuntu-latest]

    steps:
      - name: Traer repo
        uses: actions/checkout@v4

      - name: Usar nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Instalar dependencias
        working-directory: ./calculadora
        run: npm install

      - name: Ejecutar pruebas
        working-directory: ./calculadora
        run: npm test
